export type HolderShipVisualId = 'standard' | 'doge-runner' | 'void-interceptor' | 'sovereign-wraith' | 'eclipse-corvette' | 'abyssal-driller' | 'hero-archimedes' | 'hero-zebra' | 'hero-rainmaker'

export interface HolderShipVisual {
  id: HolderShipVisualId
  name: string
  description: string
  requiredTier: number
}

export const HOLDER_SHIP_VISUALS: readonly HolderShipVisual[] = [
  {
    id: 'standard',
    name: 'Standard Hull',
    description: 'Use the normal ship hull for your selected craft.',
    requiredTier: 0,
  },
  {
    id: 'doge-runner',
    name: 'Doge Runner Mk II',
    description: 'T2 holder-only gold racing hull. Stats stay unchanged.',
    requiredTier: 2,
  },
  {
    id: 'void-interceptor',
    name: 'Void Interceptor',
    description: 'T3 holder-only visual hull. Stats stay unchanged.',
    requiredTier: 3,
  },
  {
    id: 'sovereign-wraith',
    name: 'Sovereign Wraith',
    description: 'T3 holder-only sovereign heavy fighter. Stats stay unchanged.',
    requiredTier: 3,
  },
  {
    id: 'eclipse-corvette',
    name: 'Eclipse Corvette',
    description: 'T3 holder-only command ship hull. Stats stay unchanged.',
    requiredTier: 3,
  },
  {
    id: 'abyssal-driller',
    name: 'Deep Core Mining Ring',
    description: 'T3 holder-only oversized deep-core mining rig. Stats stay unchanged.',
    requiredTier: 3,
  },
  // --- Hero hulls: the only ships in the game not generated by a script in scripts/.
  //
  // These three are licensed third-party art (Viktor Hahn's Naev ship3d models, CC BY 4.0), and CC-BY
  // obliges us to name the author, the work and the licence wherever the work appears. The author and
  // licence therefore live in `description`, which the station HANGAR row renders verbatim — that is
  // the one place a player who is looking AT the hull can read who made it. Do not trim these strings
  // down to match the house style of the rows above; the wording is the licence condition, not flavour.
  // The full attribution with source and licence URLs is in README.md and wiki.html.
  {
    id: 'hero-archimedes',
    name: 'Archimedes',
    description: 'T3 hero hull — model by Viktor Hahn (Naev), CC BY 4.0. Stats stay unchanged.',
    requiredTier: 3,
  },
  {
    id: 'hero-zebra',
    name: 'Zebra',
    description: 'T3 hero hull — model by Viktor Hahn (Naev), CC BY 4.0. Stats stay unchanged.',
    requiredTier: 3,
  },
  {
    id: 'hero-rainmaker',
    name: 'Rainmaker',
    description: 'T3 hero hull — model by Viktor Hahn (Naev), CC BY 4.0. Stats stay unchanged.',
    requiredTier: 3,
  },
] as const

const STORAGE_KEY = 'scc.holderShipVisual.v1'

type StorageLike = Pick<Storage, 'getItem' | 'setItem'>

export function holderShipVisualById(id: string | null): HolderShipVisual | null {
  return HOLDER_SHIP_VISUALS.find((visual) => visual.id === id) ?? null
}

export function holderShipVisualsForTier(tier: number): readonly HolderShipVisual[] {
  const t = Math.max(0, Math.floor(tier))
  return HOLDER_SHIP_VISUALS.filter((visual) => visual.requiredTier <= t)
}

export function resolveHolderShipVisual(id: string | null, tier: number): HolderShipVisual {
  const visual = holderShipVisualById(id)
  return visual && visual.requiredTier <= Math.max(0, Math.floor(tier))
    ? visual
    : HOLDER_SHIP_VISUALS[0]
}

export function loadHolderShipVisual(storage: StorageLike): HolderShipVisualId {
  try {
    const stored = storage.getItem(STORAGE_KEY)
    return holderShipVisualById(stored)?.id ?? 'standard'
  } catch {
    return 'standard'
  }
}

export function saveHolderShipVisual(storage: StorageLike, id: HolderShipVisualId): void {
  try {
    storage.setItem(STORAGE_KEY, id)
  } catch {
    // Cosmetic preference only; ignore private-mode/storage failures.
  }
}
